[김기현] add : kakao_login
wecode-bootcamp-korea/30-2nd-YourHomeIsMine-backend pull request #2
Opened 2022-03-16 08:03 UTC by tanonkim

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 로그인 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 카카오 REST API 를 이용하여 회원정보 요청
- get_or_create 메소드를 사용하여 데이터베이스 관리
<img width="1266" alt="스크린샷 2022-03-16 오후 5 02 07" src="https://user-images.githubusercontent.com/60570733/158543861-583554c8-8819-423a-b497-8b88b76754e5.png">
<img width="1615" alt="스크린샷 2022-03-16 오후 5 02 25" src="https://user-images.githubusercontent.com/60570733/158543871-aa6af500-dbef-45f9-ac8e-d83bf17c4e5b.png">

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항

2022-03-19 06:36 UTC, tanonkim commented
## OAuth

### Flow
__1. 준비__
- Client(YourHomeIsMine)는 OAuth를 제공하는 Resource Server(Kakao)의 개발자 콘솔에 서비스를 등록하고 client_id와 client_secret을 발급합니다. 그리고 redirect_url을 등록합니다.

__2. Get Authorization Code__

- Client는 client_id와 redirect url, 그리고 권한 목록(이메일 등)의 정보들 등록해 로그인 버튼을 생성하빈다.
- User가 권한 승인과 더불어 로그인에 성공하면 Resource Server는 위에서 입력한 redirect url로 authorization code를 전달합니다.
이때 authorization code는 사용자 정보에 접근할 수 없고, 사용자 정보에 접근할 수 있는 access_token을 획득하기 위해 사용합니다.

__3. Get Access Token__
Client는 정해진 시간(24시간 미만) 이내에 cliend_id, redirect url, authorization code와 client_secret을 포함한 요청을 Resource Server에 보내면 access_token을 획득할 수 있습니다.

__4. Access 사용자 정보 및  Use API__
Client는 access_token을 이용해 사용자가 권한을 허럭한 정보에 접근합니다.


### Front-End
프론트엔드는 위 과정 중 1~3번에 해당하는 작업을 진행해 access_token을 백엔드에 전달합니다.

### Back-End
백엔드는 프론트엔드에서 전달받은 access_token을 이용해 Resource Server에 등록된 사용자의 정보(unique_index)를 가져옵니다.

위에서 언급한 unique index와 인증을 진행한 Resource Server의 종류(예 : kakao 등)의 종류를 user table에 저장해 사용자를 생성하고 식별합니다.

2022-03-19 14:47 UTC, Kang-kyunghun requested changes

2022-03-19 14:47 UTC, Kang-kyunghun commented on users/tests.py
> +from my_settings import SECRET_KEY, ALGORITHM
```suggestion
from users.models  import User
from my_settings   import SECRET_KEY, ALGORITHM
```

2022-03-19 14:47 UTC, Kang-kyunghun commented on users/views.py
> +
```suggestion
```
공백은 1줄로 해주세요.

2022-03-19 14:47 UTC, Kang-kyunghun commented on users/views.py
> +            )
```suggestion
                defaults={
                    'email'         : email,
                    'nickname'      : nickname,
                    'profile_image' : profile_image,
                    'gender'        : gender
                }
            )
```

2022-03-19 14:47 UTC, Kang-kyunghun commented on users/views.py
> +            user.save()
user.save()을 한 이유가 있나요?

2022-03-19 14:47 UTC, Kang-kyunghun commented on users/views.py
> +                    }, SECRET_KEY, ALGORITHM)
```suggestion
            payload = {
                'user_id' : user.id, 
                'exp': datetime.datetime.utcnow() + datetime.timedelta(hours=24)
            }    
            access_token = jwt.encode(payload, SECRET_KEY, ALGORITHM)
```

2022-03-19 14:47 UTC, Kang-kyunghun commented on users/views.py
> +                    }
```suggestion
            results = {
                'email'         : email,
                'nickname'      : nickname,
                'profile_image' : profile_image,
                'gender'        : gender,
                'kakao_id'      : kakao_id
            }               
```

2022-03-19 14:47 UTC, Kang-kyunghun commented on users/views.py
> +            profile_request = requests.get(
request의 결과가 error일 때도 처리해 주세요.

2022-03-19 16:13 UTC, tanonkim commented on users/tests.py
> +from my_settings import SECRET_KEY, ALGORITHM
수정하였습니다!!

2022-03-19 16:13 UTC, tanonkim commented on users/views.py
> +
네! 수정완료하였습니다~

2022-03-19 16:14 UTC, tanonkim commented on users/views.py
> +            )
convention 수정 완료하였습니다.

2022-03-19 16:14 UTC, tanonkim commented on users/views.py
> +            user.save()
get을 get_or_create로 바꾸면서 미처 놓쳤습니다!
삭제하였습니다~

2022-03-19 16:17 UTC, tanonkim commented on users/views.py
> +                    }, SECRET_KEY, ALGORITHM)
다음부터는 payload를 활용해 클린하게 짜겠습니다!!
수정완료했습니다!

2022-03-19 16:17 UTC, tanonkim commented on users/views.py
> +                    }
컨벤션에 조금 더 신경써야 할 것 같습니다!
수정완료하였습니다~

2022-03-19 16:30 UTC, tanonkim commented on users/views.py
> +            profile_request = requests.get(
네!
추가완료하였습니다!!

2022-03-21 02:48 UTC, Kang-kyunghun commented
- 아주 작은 수정 사항 있습니다. 그것만 수정하면 될 것 같습니다.
- 소셜로그인 관련해서 읽어보면 좋을 것 같아서 링크 보내드려요. 조사하는라 고생하셨어요.
- https://www.jessym.com/articles/stateless-oauth2-social-logins-with-spring-boot

2022-03-21 08:33 UTC, Kang-kyunghun requested changes

2022-03-21 08:33 UTC, Kang-kyunghun commented on users/urls.py
> +    path("/login/kakao/callback", KakaoCallback.as_view()),
```suggestion
    path("/login/kakao", KakaoCallback.as_view()),
```

2022-03-21 08:33 UTC, Kang-kyunghun commented on users/views.py
> +class KakaoCallback(View):
```suggestion
class KakaoSignIn(View):
```

2022-03-21 08:38 UTC, Kang-kyunghun commented
LGTM~~~!

2022-03-21 08:38 UTC, merged

2022-03-21 10:40 UTC, tanonkim commented on users/urls.py
> +    path("/login/kakao/callback", KakaoCallback.as_view()),
수정완료했습니다

2022-03-21 10:40 UTC, tanonkim commented on users/views.py
> +class KakaoCallback(View):
수정완료했습니다