[윤명국] add: list api
wecode-bootcamp-korea/30-2nd-YourHomeIsMine-backend pull request #7
Opened 2022-03-18 06:03 UTC by kkookkss

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
RoomList API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. room list page
- room list 페이지에 필요한 정보를 room별로 전달되도록 구현
- front와 통신하여 화면 구현까지 확인

2. 페이지 기능 구현
- limit, offset을 이용하여 페이지 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 페이징하는 방법 중  limit, offset을 이용하여 페이징하는 방법을 알게 되었습니다.
- datetime module과 strftime method 사용 방법을 알게 되었습니다.
- order_by method 사용 방법을 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-03-22 03:49 UTC, Kang-kyunghun requested changes

2022-03-22 03:49 UTC, Kang-kyunghun commented on rooms/views.py
> +from rooms.models      import Room, RoomAmenity, RoomHouseRule, RoomSchedule
import 하는 package 순서 다시 정리해 주세요.
1. python 자체 package
2. Pip install로 설치한 package
3. 내가 만든 package

2022-03-22 03:49 UTC, Kang-kyunghun commented on rooms/views.py
> +        offset         = (page*20)
20으로 정해지면, limit을 자유롭게 사용하지 못합니다.
```suggestion
        offset         = (page*limit)
```

2022-03-22 03:49 UTC, Kang-kyunghun commented on rooms/views.py
> +                            .filter(q)[offset:offset+limit]
q을 사용하는 이유는 filter 조건을 하나로 만들기 위해서 입니다. 현재 filter()에 들어가 있는 조건들을 전부 q로 만들어 주세요.

2022-03-22 03:50 UTC, Kang-kyunghun commented
1. filter들을 q로 정리해 주세요.
2. 나머지는 내일 라이브코드 리뷰 시간에 더 자세히 보겠습니다.

2022-03-23 01:50 UTC, kkookkss commented on rooms/views.py
> +        offset         = (page*20)
확인했습니다

2022-03-23 08:08 UTC, kkookkss commented on rooms/views.py
> +from rooms.models      import Room, RoomAmenity, RoomHouseRule, RoomSchedule
확인했습니다

2022-03-23 08:08 UTC, kkookkss commented on rooms/views.py
> +                            .filter(q)[offset:offset+limit]
확인했습니다

2022-03-23 09:31 UTC, Kang-kyunghun requested changes

2022-03-23 09:31 UTC, Kang-kyunghun commented on rooms/views.py
> +
공백 한 줄 제거

2022-03-23 09:33 UTC, kkookkss commented on rooms/views.py
> +
확인했습니다~!

2022-03-24 00:17 UTC, Kang-kyunghun commented
LGTM~!!

2022-03-24 00:17 UTC, merged