[김은지] fix : conventions and pagination
wecode-bootcamp-korea/30-2nd-YourHomeIsMine-backend pull request #9
Opened 2022-03-18 08:58 UTC by thisiseunji

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- pagination 적용

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. review get 요청시 pagination 적용

2022-03-18 09:06 UTC, thisiseunji commented
경훈님 테스트 코드 작성해서 다시 피알 올리겠 습니다~~!

2022-03-18 11:40 UTC, thisiseunji commented
'created_at' 컬럼 제외하고 get 테스트 완료 했습니다~!

2022-03-19 14:50 UTC, Kang-kyunghun requested changes

2022-03-19 14:50 UTC, Kang-kyunghun commented on reviews/views.py
> +            offset  = int(request.GET.get('offset', 0))*6
offset에 *6이 있는 이유가 무엇일까요?

2022-03-19 14:50 UTC, Kang-kyunghun commented on config/urls.py
> +    path('rooms/<int:room_id>/reviews', include('reviews.urls')),
여기서 요청해도 되지만, room.urls에 적용하면 좋을 것 같아요.

2022-03-19 14:50 UTC, Kang-kyunghun commented on reviews/tests.py
> +from rooms.models   import *
* 대신에 필요한 것만 불러와 주세요.

2022-03-20 02:28 UTC, thisiseunji commented on reviews/views.py
> +            offset  = int(request.GET.get('offset', 0))*6
프론트에서 '페이지'를 offset으로 받아서 페이지네이션을 처리하려고 했습니다.

2022-03-20 02:29 UTC, thisiseunji commented on config/urls.py
> +    path('rooms/<int:room_id>/reviews', include('reviews.urls')),
넵~! 수정하겠습니다!

2022-03-20 02:29 UTC, thisiseunji commented on reviews/tests.py
> +from rooms.models   import *
넵~! 수정하겠습니다.

2022-03-21 03:03 UTC, Kang-kyunghun commented on reviews/views.py
> +            offset  = int(request.GET.get('offset', 0))*6
6을 그대로 하드코딩을 해버리면 기획이 바꼈을 때 코드를 수정해야 됩니다.
페이지를 받는다고 하면 아래와 같이 수정해야 할 것 같습니다.
```suggestion
            page  = int(request.GET.get('page', 1))
            offset = (page-1) * limit           
```

2022-03-21 04:53 UTC, thisiseunji commented on reviews/views.py
> +            offset  = int(request.GET.get('offset', 0))*6
넵 말씀해주신대로 수정하겠습니다!

2022-03-23 01:59 UTC, merged